<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="7aaf43a4-1f76-473c-8b6b-fd80b5c860b7" name="Cdo@CDOVPC01 2010-06-08 16:42:14" runUser="CDOVPC01\Cdo" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2006">
  <TestRunConfiguration name="Local Test Run" id="a8a2e672-9ca4-4527-a674-628eb5bad686">
    <Description>This is a default test run configuration for a local test run.</Description>
    <Timeouts testTimeout="300000" />
    <Deployment runDeploymentRoot="C:\Cdo\CodePlex\TxFileManager\TestResults\Cdo_CDOVPC01 2010-06-08 16_42_14">
      <DeploymentItem filename="C:\Cdo\CodePlex\TxFileManager\ChinhDo.Transactions.FileManager\bin\Debug\ChinhDo.Transactions.dll" />
    </Deployment>
    <TestTypeSpecific />
  </TestRunConfiguration>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <Times creation="2010-06-08T16:42:14.1055888-04:00" queuing="2010-06-08T16:42:14.7465104-04:00" start="2010-06-08T16:42:15.0569568-04:00" finish="2010-06-08T16:42:15.7679792-04:00" />
  <TestDefinitions>
    <UnitTest name="CanHandleCopyErrors" storage="c:\cdo\codeplex\txfilemanager\chinhdo.transactions.filemanagertest\bin\debug\chinhdo.transactions.filemanagertest.dll" id="6fecc392-c30e-5f7b-3615-b4cfe7262b04">
      <Css projectStructure="" iteration="" />
      <Owners>
        <Owner name="" />
      </Owners>
      <Execution id="f99476cb-0b40-4e48-91a8-3a0ca7b4d135" />
      <TestMethod codeBase="C:\Cdo\CodePlex\TxFileManager\ChinhDo.Transactions.FileManagerTest\bin\Debug\ChinhDo.Transactions.FileManagerTest.dll" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="ChinhDo.Transactions.FileManagerTest.FileManagerTest, ChinhDo.Transactions.FileManagerTest" name="CanHandleCopyErrors" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="6fecc392-c30e-5f7b-3615-b4cfe7262b04" executionId="f99476cb-0b40-4e48-91a8-3a0ca7b4d135" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="f99476cb-0b40-4e48-91a8-3a0ca7b4d135" testId="6fecc392-c30e-5f7b-3615-b4cfe7262b04" testName="CanHandleCopyErrors" computerName="CDOVPC01" duration="00:00:00.0774017" startTime="2010-06-08T16:42:15.1370720-04:00" endTime="2010-06-08T16:42:15.6177632-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d">
      <Output>
        <ErrorInfo>
          <Message>Test method ChinhDo.Transactions.FileManagerTest.FileManagerTest.CanHandleCopyErrors threw exception:  System.IO.IOException: The process cannot access the file 'C:\Documents and Settings\Chinh Do\Local Settings\Temp\CdFileMgr\-51ff99b1.tmp' because it is being used by another process..
Assert.AreEqual failed. Expected:&lt;0&gt;. Actual:&lt;1&gt;. Unexpected value for numTempFiles.</Message>
          <StackTrace>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.Delete(String path)
   at ChinhDo.Transactions.FileManagerTest.FileManagerTest.CanHandleCopyErrors() in C:\Cdo\CodePlex\TxFileManager\ChinhDo.Transactions.FileManagerTest\FileManagerTest.cs:line 365

TestCleanup Stack Trace
   at ChinhDo.Transactions.FileManagerTest.FileManagerTest.TestCleanup() in C:\Cdo\CodePlex\TxFileManager\ChinhDo.Transactions.FileManagerTest\FileManagerTest.cs:line 33
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>